[package]
name = "rustc-llvm-proxy"
version = "0.2.0"
authors = ["Denys Zariaiev <denys.zariaiev@gmail.com>"]
license = "MIT"
edition = "2018"

readme = "README.md"
description = "Dynamically proxy LLVM calls into Rust own shared library"
repository = "https://github.com/denzp/rustc-llvm-proxy"
categories = ["development-tools::build-utils", "external-ffi-bindings"]
keywords = ["llvm"]

[badges]
appveyor = { repository = "denzp/rustc-llvm-proxy", branch = "master", service = "github" }
travis-ci = { repository = "denzp/rustc-llvm-proxy", branch = "master" }
maintenance = { status = "passively-maintained" }

[dependencies]
libloading = "0.5"
lazy_static = "1.0"
failure = "0.1"
libc = "0.2"
llvm-sys = { version = "120", features = ["no-llvm-linking", "disable-alltargets-init"] }

[build-dependencies]
cargo_metadata = "0.8"
failure = "0.1"
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
